// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkUbXluy_z2IcF0b0R0vyx-Rnknp-jYTM',
    appId: '1:620303359377:web:3f809a880078c1557e0e30',
    messagingSenderId: '620303359377',
    projectId: 'homeautomation-55779',
    authDomain: 'homeautomation-55779.firebaseapp.com',
    databaseURL:
        'https://homeautomation-55779-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeautomation-55779.firebasestorage.app',
    measurementId: 'G-5YQBWNGEGX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkUbXluy_z2IcF0b0R0vyx-Rnknp-jYTM',
    appId: '1:620303359377:ios:e54dac959f45acfb7e0e30',
    messagingSenderId: '620303359377',
    projectId: 'homeautomation-55779',
    authDomain: 'homeautomation-55779.firebaseapp.com',
    databaseURL:
        'https://homeautomation-55779-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeautomation-55779.firebasestorage.app',
  );
}
